Resources:
  ClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "first_name"
          AttributeType: "S"
        - AttributeName: "last_name"
          AttributeType: "S"
        - AttributeName: "company"
          AttributeType: "S"
        - AttributeName: "phone"
          AttributeType: "S"
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "text_box"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "first_name"
          KeyType: "HASH"
        - AttributeName: "last_name"
          KeyType: "HASH"
        - AttributeName: "phone"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "clients"


